name: Deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: add actions
        uses: actions/checkout@v3
        uses: actions/node-setup@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: run test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu
    steps:
      uses: actions/checkout@v3
      uses: actions/node-setup@v3
      with:
        node-version: 16
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: pushing to aws
        run: echo "pushing to aws"
      
        
    
